export const queryKeys = {
  me: ["me"] as const,
  projects: ["projects"] as const,
  project: (id: string) => ["projects", id] as const,
  projectRoles: (id: string) => ["projects", id, "roles"] as const,
  projectCredentials: (id: string) => ["projects", id, "credentials"] as const,
  projectEnvironments: (id: string) => ["projects", id, "environments"] as const,
  modules: (projectId: string) => ["projects", projectId, "modules"] as const,
  modulesHub: ["modules-hub"] as const,
  module: (id: string) => ["modules", id] as const,
  moduleWithRelations: (id: string) => ["modules", id, "detail"] as const,
  discovery: (moduleId: string) => ["modules", moduleId, "discovery"] as const,
  workflows: (moduleId: string) => ["modules", moduleId, "workflows"] as const,
  testCases: (moduleId: string) => ["modules", moduleId, "test-cases"] as const,
  testRuns: (moduleId: string) => ["modules", moduleId, "test-runs"] as const,
  testRun: (testRunId: string) => ["test-runs", testRunId] as const,
  report: (moduleId: string) => ["modules", moduleId, "report"] as const,
};